  name: matrix
  on:
    pull_request:
      branches: [ 'main' ]
      types: [opened, synchronize, reopened, closed, labeled, unlabeled]

  jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          platform:
            - i386 
            - arm64v8
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2  

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Generate Tag Output
          id: tag_output
          run: echo "::set-output name=tag::${{ matrix.platform }}"

        # Login against a Docker registry except on PR
        # https://github.com/docker/login-action
        - name: Log into
          uses: docker/login-action@v2
          with:
            username: serbenyuk
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        # Extract metadata (tags, labels) for Docker
        # https://github.com/docker/metadata-action
        - name: Extract Docker metadata
          id: meta
          uses: docker/metadata-action@v4.4.0
          with:
            images: serbenyuk/new
            labels: |
              org.opencontainers.image.revision=${{ env.SHA }}
            tags: |
              type=edge,branch=$repo.default_branch
              type=semver,pattern=v{{version}}
              type=sha,prefix=,suffix=,format=short
        
        # Build and push Docker image with Buildx (don't push on PR)
        # https://github.com/docker/build-push-action
        - name: Build and push Docker image
          id: build
          uses: docker/build-push-action@v4.0.0
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

    display_matrix_outputs:
      name: Display Matrix Outputs
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Check Out Code
          uses: actions/checkout@v2

        - name: Initialize Outputs List
          id: outputs_list
          run: echo "::set-output name=outputs::"

        - name: Append Outputs to List
          run: |
            outputs_list="${outputs_list} ${{ needs.build.outputs.tag }} "

        - name: Display All Outputs
          run: |
            echo "All Outputs:"
            echo "${{ steps.outputs_list.outputs.outputs }}"